# Mysql数据库地址
MYSQL_HOST: "8.134.198.35"

# Mysql数据库端口
MYSQL_PORT: 3306

# Mysql数据库用户名
MYSQL_USER: "root"

# Mysql数据库密码
MYSQL_PASSWORD: "@Xie12345678"

# Mysql数据库名称
MYSQL_DATABASE: "webtest"
# MYSQL_DATABASE: "aisystem"

OPENAI_API_BASE: ""

OPENAI_API_KEY: "bb31c847833849cdb9430d02e94498f7.CurNG3U3QgolKeIO"

# 向量模型名称
OPENAI_API_MODEL_EMBEDDING: "embedding-3"

# 自然语言处理模型
OPENAI_API_MODEL_GLM4: "GLM-4-Flash"

# 最大线程数
MAX_THREADING: 10

# 请求间隔，单位：秒
REQUEST_INTERVAL: 10

# 项目名称
PROJECT_NAME: "Heypon需求向量框架"

# 项目描述
PROJECT_DESC: "将需求文档拆分转成向量数据，并用Mysql维护数据与向量之间的管理，向量数据存本地"

REQUIREMENTS_NAME: [
  '药声通学习中心.docx',
]

# 向量数据库路径
FAISS_DB_PATH: "requirements_vectors.faiss"

# 相似度阈值
SIMILARITY_THRESHOLD: 0.65

# 总结提炼设定长度值
SUMMARY_LENGTH: 300

# 执行任务 1 代表处理需求文档及处理向量数据  2 代表在向量数据中查找相似需求文档  3 新的处理文档逻辑
EXECUTE_TASK: "2"

# 统计分词的长度。 注意：如何设置的过长，可能导致漏掉某些需求内容
N-GRAM: 2

# 统计分词热度的比率，一般设置为0就行，如有实际需要可自己更改值，为整数
TOP_N: 0