
# 项目名称
PROJECT_NAME: "Heypon需求向量框架"

# 项目描述
PROJECT_DESC: "将需求文档拆分转成向量数据，并用Mysql维护数据与向量之间的管理，向量数据存本地"

REQUIREMENTS_NAME: [
  '答题表单.docx',
  '日期筛选组件.docx',
  '下载word节点重新生成文件.docx',
  '会签求和批量导出.docx',
  '会签求和结果表单导出.docx',
  '图像识别组件.docx',
  '批次详情会签节点操作人完成情况.docx',
  '支持申请人.docx',
  '销售对话卡片.docx'
]

TEST_CASES_NAME: [

]

# 向量模型分析最大线程
MAX_THREADING: 10

# 向量模型分析请求间隔，单位：秒
REQUEST_INTERVAL: 10

